### ISSUE TITLE
VSCode launch.json console option is not allowed

### ISSUE THREAD

**Issue by renjithis** [varigit/var-demos#2]
I am using VSCode 1.89.0 on ubuntu 22.04
When I tried setting up a test project for cross-compilation with remote debugging using the tutorial, I got a VSCode warning in launch.json, line:
`        "console": "integratedTerminal",`
> Property console is not allowed.

**Comment by morishitaandre** [comment]
Hi @renjithis,

The "console" attribute is not part of the C/C++ debugging attributes as listed [here](https://code.visualstudio.com/docs/cpp/launch-json-reference) - this is why this warning appears. Since VSCode is ignoring this line, you can simply remove it and it won't affect the tutorial.

We will soon be updating the launch.json file. Thanks for the feedback!
